### ISSUE TITLE
개발 환경 세팅

### ISSUE THREAD

**Issue by namhyo01** [boostcampwm-2022/web34-moheyum#14]
- FE
  - Next.js
  - Recoil
  - Emotion
  - ThemeProvider
  - Typescript
  - ESLint + Prettier
  - https://github.com/boostcampwm-2022/web34-moheyum/issues/19
- BE
  - Nest.js
  - Prisma + MongoDB
  - MongoDB 별도 서버 세팅
    - #18

**Comment by 906bc906** [comment]
next issue: #15

**Comment by 906bc906** [comment]
- BE
  - MongoDB 별도 서버 세팅

**Comment by 906bc906** [comment]
브랜치 이름

`feat/14-dev-setting`
