### ISSUE TITLE
CSS 깨지는 버그

### ISSUE THREAD

**Issue by namhyo01** [boostcampwm-2022/web34-moheyum#156]

**Comment by namhyo01** [comment]
CSS가 깨지는 버그들이 많습니다
ex) 긴 글...

**Comment by leesunmin1231** [comment]
## 문제상황
긴 텍스트의 경우 본문과 댓글이 겹쳐 보임

## 해결 방법
크게 감싼 부분 (mainSectionWrapper) 에 높이 100%가 지정되어 있었음. (필수적인 부분이라 빼는게 불가능)
mainSection 내부를 크게 3개의 컴포넌트로 분리
부모 post
본문
댓글
그리고 각각의 컴포넌트 내에서 구체적인 내용을 담음

## 문제상황
사용자 프로필 정보에서 아이디와 닉네임이 width를 넘어가면 자동으로 줄바꿈이 됨.

## 해결방법
- 줄바꿈 방지
white-space: nowrap;

- 텍스트가 부모 컴포넌트 width를 넘치는 경우
부모 컴포넌트 width요소를 min-content로 준다.
width:min-content

참고:
https://www.daleseo.com/css-width/

**Comment by leesunmin1231** [comment]
- 완료
