### ISSUE TITLE
Article Card형식에 유저 image, 닉네임, 아이디, 시간등을 UI 수정 및 표시

### ISSUE THREAD

**Issue by namhyo01** [boostcampwm-2022/web34-moheyum#160]

**Comment by leesunmin1231** [comment]
html에서 텍스트가 기본적으로 줄이 넘어갈때 단어 단위로 잘려서 넘어가게 되어 있음. 
따라서 띄어쓰기 하지 않고 글을 쓴다면 한단어로 인식해서 width를 넘어가도 줄바꿈이 되지 않음

css에 아래 내용을 추가하면 한단어여도 width를 넘어가면 단어를 잘라서 줄바꿈을 하게 됨
word-break: break-all;

반대로 줄바꿈을 하면 안되는경우 
white-space: nowrap;

**Comment by leesunmin1231** [comment]
- 완료
