### ISSUE TITLE
마크다운 프리뷰 모드에서 게시글 작성이 되지 않음

### ISSUE THREAD

**Issue by 906bc906** [boostcampwm-2022/web34-moheyum#177]
## 버그 설명

버그 재현 방법과 스크린샷을 반드시 기재해주세요.

(가능한 경우) 예상되는 행동과 실제로 발생하는 행동도 기재해주세요.

## 버그 해결 과정

이 영역은 해당 코드의 책임자가 본인인 경우, 또는 간단하게 수정할 수 있는 경우에만 작성해주세요.

오타와 같은 간단하게 해결할 수 있는 문제는 본인의 코드가 아니더라도 직접 수정하고 해당 코드 책임자에게 수정했음을 알려주세요.

본인의 코드가 아니가 간단하게 해결할 수 없는 문제인 경우 blame으로 해당 코드 작성자 파악하여 assign한 후 버그가 발생했음을 알려주세요.

**Comment by prayinforrain** [comment]
에디터 레이아웃 수정시에 같이 반영하겠습니다
