### ISSUE TITLE
메인페이지 - 사이드바

### ISSUE THREAD

**Issue by leesunmin1231** [boostcampwm-2022/web34-moheyum#36]
- sidebar
- [x] 홈: 메인으로 라우팅
- [x] 알림: 버튼만
- [x] 검색: 버튼만
- [x] 프로필: 사용자 본인 프로필 띄우기
- [x] 설정: 드롭다운
    - [ ] 내 계정 정보 확인
    - [ ] 비밀 번호 변경 기능
    - [x] 알림 일시중지 : 버튼만
    - [ ] 로그아웃

**Comment by leesunmin1231** [comment]
## 트러블 슈팅 과정

```jsx
import Image from 'next/image';
<Image src="/logo_white.svg" alt="Logo" width={450} height={150} />
```

- Image태그를 쓰면서 느낀 상당히 불편한점은 반드시 너비와 높이를 지정해줘야한다. 그것도 픽셀만 가능하다
- CLS자동 방지해준다는 점에서 성능 좋게 하려고 하는건 알겠는데, 그렇다면 반응형에는 어떻게 담아야하는 걸까?
- 아래는 구글링을 통해 찾은 자료이다.

next/image에 크기를 명시하는 방법은 3가지가 있습니다.

1. static import 를 사용하기
2. remote 이미지를 사용하는 경우, heigth, width 속성 표기
3. layout='fill' 사용해서 부모 element 크기와 맞추기 ( 이미지 크기를 모르는 경우 사용 )

[[https://happyer16.tistory.com/entry/Next-이미지-최적화-Image-Component-and-Image-Optimizatio](https://happyer16.tistory.com/entry/Next-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%B5%9C%EC%A0%81%ED%99%94-Image-Component-and-Image-Optimizatio)](https://happyer16.tistory.com/entry/Next-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%B5%9C%EC%A0%81%ED%99%94-Image-Component-and-Image-Optimization)

3번째 방법을 써보기로 했다.

```jsx
<Image src="/logo_purple.svg" alt="Logo" layout="fill" priority />
```

- 이렇게 하니 콘솔에 경고가 뜨더라.
- next/legacy/image 를 쓰라고 한다.

`import Image from 'next/legacy/image'`

공식 문서를 찾아보니 Next 13버전에 나온 next/image의 업그레이드 버전이라고 한다.

[https://nextjs.org/docs/api-reference/next/legacy/image](https://nextjs.org/docs/api-reference/next/legacy/image)

따라서 최종 코드는 다음과 같이 수정했다.

```jsx
import Image from 'next/legacy/image'
<Image src="/logo_purple.svg" alt="Logo" layout="fill" priority />
```

- priority를 지정하면 next가 이미지 로딩을 우선시 해준다고한다.

- [추가 학습 자료](https://polarlsm.notion.site/image-930bf9f11aac4bbf9a27a52059f85808)

**Comment by leesunmin1231** [comment]
style에 themeprovider 적용이 안되는 이유를 찾았다.

Refs

[https://stackoverflow.com/questions/70828179/emotion-react-themeprovider-doesnt-work](https://stackoverflow.com/questions/70828179/emotion-react-themeprovider-doesnt-work)

type 지정을 안해줘서 그런거였다….

```jsx
// types/Theme.ts

import '@emotion/react'; // it's important to use ThemeProvider

type themeType = {
  backgroundColor: string;
  width: string;
};

declare module '@emotion/react' {
  export interface Theme {
    sidebar: themeType;
    mainSection: themeType;
  }
}
```

이런식으로 본인이 사용할 Theme 타입을 emotion 모듈에 지정해줘야한다.

그리고 theme을 정의 할때 위에서 지정해준 타입을 선언해준다

```jsx
// styles/theme.ts

import { Theme } from '@emotion/react';

const theme: Theme = {
  sidebar: {
    backgroundColor: COLORS.PRIMARY_LIGHT,
    width: `${sidebarSize}%`,
  },
  mainSection: {
    backgroundColor: COLORS.WHITE,
    width: `${100 - sidebarSize}%`,
  },
};
```

이렇게 하면 ThemeProvider로 감싼 모든 컴포넌트에서

```jsx
const Wrapper = styled.aside`
  width: ${({ theme }) => theme.sidebar.width};
  height: 100%;
  ${displayCenter}
  background-color: ${({ theme }) => theme.sidebar.backgroundColor};
`;
```

이와 같이 쓸 수 있다.

위에서 지정해둔 타입들만 사용할 수 있으므로 다른 추가적인 스타일이 필요하면 타입을 수정해줘야한다.

**Comment by prayinforrain** [comment]
#197 PR에서 구현을 완료해서 이슈 닫습니다
