### ISSUE TITLE
CI - 프론트엔드 라이트하우스 성능 테스트

### ISSUE THREAD

**Issue by leesunmin1231** [boostcampwm-2022/web34-moheyum#51]
프론트엔드 라이트하우스 성능 테스트를 깃헙액션으로 자동화
PR보내면 PR댓글로 성능 테스트 결과가 나오도록 자동화

**Comment by leesunmin1231** [comment]
## 후에 추가해야 할 부분

우리 서비스는 로그인이 필요한 서비스라 [puppeteer](https://pptr.dev/) 사용해서 로그인 후 Lighthouse 실행할 수 있도록 바꿔야 한다.

현재는 로그인 안해도 메인페이지 로딩이 되서 일단 이렇게 해놨다.

**Comment by prayinforrain** [comment]
11/21 월요일 스크럼에서 제거하기로 결정해서 닫겠습니다

**Comment by leesunmin1231** [comment]
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/81913106/202943206-f1e3ee75-1f07-404f-9f0b-61232015a750.png">

- Lighthouser CI에서 오류가 남
- api 서버가 동작 안하고 있어서 오류가 나나 싶어 pm2로 서버 동작 시킨 후 라이트하우스 돌려봄 => 실패
- 테스트 환경에서 시간 초과로 라이트하우스가 오류 처리 하는건가 싶어 maxWaitForLoad, maxWaitForFcp 값을 길게 설정해줌 => 실패

원인 을 찾지 못하여 제거하기로 결정
