### ISSUE TITLE
팔로워/팔로잉 기능 추가

### ISSUE THREAD

**Issue by prayinforrain** [boostcampwm-2022/web34-moheyum#63]
FE  
- https://github.com/boostcampwm-2022/web34-moheyum/issues/72

**Comment by 906bc906** [comment]
FE
- 게시글의 작성자 이름을 눌렀을 때 해당 작성자의 프로필로 이동해야함 (팔로우 할 수 있기 위해)
- 유저 프로필에서
  - 내 계정인 경우 팔로우 버튼이 없고 프로필 편집 버튼이 있어야 함
  - 타인의 계정인 경우 팔로우/팔로우 취소 버튼이 있어야 함
  - 게시글 목록을 확인할 수 있어야 하며 전체 목록에서 보여지는 게시글 단위에서 별도의 편집을 해야되는 요소는 없음
