### ISSUE TITLE
user정보 제공

### ISSUE THREAD

**Issue by namhyo01** [boostcampwm-2022/web34-moheyum#83]
- [x] 유저 정보 조회
- 프로필 사진,
- 닉네임
- bio (소개)
- user id
- email
- [x] 개인 정보 수정

**Comment by leesunmin1231** [comment]
학습 정리

- [mongoDB](https://polarlsm.notion.site/MongoDB-504ab039b9c94d1fbde04db3ec272c90)
- [TypeScript](https://polarlsm.notion.site/TypeScript-9c19b80a30f94196a699122994f93537)
- [nest](https://polarlsm.notion.site/nest-f47c483d0b0e415a907a0c6e95af63a9)
